### ISSUE TITLE
Validation fails on requests/responses with no body

### ISSUE THREAD

**Issue by shelbyallen** [alecsammon/php-raml-parser#109]
The RequestValidator class does not appear to handle validating requests without a body defined in the RAML (e.g. a standard GET request).

Calling validateRequest() will result in an error like the one below because no content-type header is set and therefore there are no bodies that match:
> Schema for GET /test with content type  was not found in API definition

The ResponseValidator class also appears to have the same issue when validating responses without a body defined (e.g. for a 204 response).

Is there any reason why this would be the intended behavior? When the content-type header is not set on the request/response object, the body validation should just get skipped, shouldn't it?

**Comment by NateEag** [comment]
I'm having the same issue with validating GET requests.

My first thought for a workaround was to make a subclass and extend `RequestValidator::assertValidBody()` so I could just skip the body validation for GET requests, but that won't work, since `assertValidBody()` is declared `private`.

If I bypass validations for GET requests, I miss out on parameter validations. I could write the parameter validations manually, but that seems to defeat the whole point of this class.

It seems to me the right thing to do here is to treat request body schemas/types as optional, since both [the 0.8 spec](https://github.com/raml-org/raml-spec/blob/master/versions/raml-08/raml-08.md#schemas) and [the 1.0 spec](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#applying-resource-types-and-traits) describe them as optional.

Thus, if no schema is found for a given resource/method/content-type, I suggest body validation should do nothing instead of throwing an exception.

Would a PR implementing that behavior be accepted?

**Comment by jefferson-lima** [comment]
I made a [pull request](https://github.com/alecsammon/php-raml-parser/pull/114) that fixes this issue

**Comment by jefferson-lima** [comment]
@martin-georgiev , can we close this issue now?
